web/config/routes.rb
Rails.application.routes.draw do
  get 'store/browse'

  devise_for :users
  resources :users

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/signup" => "devise/registrations#new"
    root 'pages#dashboard'
    get 'pages/dashboard'
    post 'transfer/transfer' => 'transfer#transfer', :as => :transfers
    get 'quiz' => 'quiz#play'
    post 'quiz' => 'quiz#get_score', :as => :play
    get 'store' => 'reward#browse'
    get 'inventory' => 'reward#inventory'
    post 'store' => 'reward#buy', :as => :browse
  end

  namespace :api do
    devise_scope :user do
      post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
      post "transfers" => "transfers#create", :as => 'transfer'
      get "transfers" => "transfers#retrieve", :as => 'retrieve'
      get "questions" => "quiz#get_questions", :as => 'questions'
      post "answers" => "quiz#process_answers", :as => 'answers'
      get "items" => "reward#get_items", :as => 'items'
      post "buy" => "reward#buy_item", :as => 'buy'
      get "inventory" => "reward#get_inventory", :as => 'inventory'
    end
  end
end

web/app/controllers/api/reward_controller.rb
class Api::RewardController < ApplicationController
  include RewardHelper

  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c|
    c.request.format == 'application/json'
  }

  respond_to :json

  def get_items
    items = Item.all.map { |i| {
        :id => i.id,
        :description => i.description,
        :image => view_context.image_path(i.image),
        :cost => i.cost,
        :consumable => i.consumable
      }
    }

    render :status => 200,
           :json => { :items => items }

  end

  def get_inventory
    inventory = []

    current_user.owned_items.each do |o|
      item = Item.find(o.item_id)
      inventory << { :id => item.id,
                     :description => item.description,
                     :consumable => item.consumable,
                     :image => view_context.image_path(item.image)
                   }
    end


    render :status => 200,
           :json => { :inventory => inventory }
  end

  def buy_item
    result = process_sale(params[:id])

    render :status => 200,
           :json => { :info => result }

  end
end

web/app/controllers/reward_controller.rb
class RewardController < AuthController
  include RewardHelper

  def browse_store
  end

  def inventory
  end

  def buy
    result = process_sale(params[:selected_item])
    flash[:notice] = result[:message]
    redirect_to :browse
  end
end

web/app/helpers/reward_helper.rb
module RewardHelper
  def process_sale(item)

    item = Item.find(item) rescue nil
    if (item == nil)
      return {:success => false, :message => "The selected item does not exist."}
    end

    if(item.cost > current_user.current_points)
      return {:success => false, :message => "You don't have enough points to buy this item."}
    end

    if(current_user.owned_items.find_by_item_id(item) && !item.consumable)
      return {:success => false, :message => "This item can only be unlocked once."}
    end

    OwnedItem.create(user_id: current_user.id, item_id: item.id)
    current_user.current_points -= item.cost
    current_user.save
    return {:success => true, :message => "You bought a " + item.description + " for £" + item.cost.to_s + "."}
  end
end

web/app/views/reward/browse.html.erb
<h1>Store</h1>
<h2>POINTS: <%= current_user.current_points %></h2>
<% Item.all.each do |i| %>
  <%= image_tag(i.image, size: "250x100", alt: "TODO: REPLACE THIS") %>
  <% if current_user.owned_items.find_by_item_id(i) && !i.consumable %>
    <h5> UNLOCKED </h5>
  <% else %>
    <%= button_to "Buy", store_path(:selected_item => i.id), :method => :post %>
  <% end %>
  <p><%= i.description%> - £<%= i.cost %></p>
<% end %>

web/app/views/reward/inventory.html.erb
<h1>Inventory</h1>
<h2>POINTS: <%= current_user.current_points %></h2>
<% current_user.owned_items.each do |i| %>
  <% item = Item.find(i.item_id) %>
  <%= image_tag(item.image, size: "250x100", alt: "TODO: REPLACE THIS") %>
  <h3><%= item.description %></h3>
  <% if item.consumable %>
  <%= button_to "Consume", store_path(:selected_item => i.id), :method => :post %>
  <% end %>
<% end %>